### ISSUE TITLE
Run JUnit5 tests with Testng

### ISSUE THREAD

**Issue by litterature** [testng-team/testng-junit5#23]
I would like to know if it's somehow possible to run Junit5 tests with TestNG in order to have the xml report. I'm working on a plugin to include in projects (with different test frameworks) to produce customized TestNG reports for tests results import in Jira Xray. TestNG xml reports offers more options than junit ones and it's why I would prefer to have all tests running through it.

**Comment by juherr** [comment]
Hi,

Thanks for your interest.

In fact, the idea behind `testng-junit5` is the opposite: not running JUnit5 tests into TestNG, but running TestNG tests into the JUnit5 Platform (kind of framework for testing libraries).

If the JUnit5 reports are not good enough in comparison to the TestNG ones, I advise you to check if something is planned on JUnit5 about reporting or open an issue there https://github.com/junit-team/junit5/
