### ISSUE TITLE
Publish SNAPSHOT of testng-junit5 artifact

### ISSUE THREAD

**Issue by sormuras** [testng-team/testng-junit5#5]
- https://oss.sonatype.org/content/repositories/snapshots/org/testng/
- https://repo1.maven.org/maven2/org/testng/

**Comment by sryll** [comment]
This seems to be have happened in the meantime, see here: https://search.maven.org/artifact/com.github.testng-team/testng-junit5/0.0.1/jar or technically: https://repo1.maven.org/maven2/com/github/testng-team/testng-junit5/

**Comment by sormuras** [comment]
True.
